import { LanguageCode, LanguageOption, Translation } from "./types";

export const LANGUAGES: LanguageOption[] = [
  { code: 'en', label: 'English', nativeLabel: 'English' },
  { code: 'hi', label: 'Hindi', nativeLabel: 'हिंदी' },
  { code: 'mr', label: 'Marathi', nativeLabel: 'मराठी' },
  { code: 'ur', label: 'Urdu', nativeLabel: 'اردو' },
  { code: 'kn', label: 'Kannada', nativeLabel: 'ಕನ್ನಡ' },
  { code: 'te', label: 'Telugu', nativeLabel: 'తెలుగు' },
];

export const SOIL_TYPES = ['Black', 'Red', 'Sandy', 'Loamy', 'Clay', 'Silt'];
export const SOIL_TEXTURES = ['Sandy', 'Loamy', 'Clay', 'Clay Loam'];
export const SOIL_COLORS = ['Black', 'Red', 'Brown', 'Yellow', 'Grey'];

export const TRANSLATIONS: Record<LanguageCode, Translation> = {
  en: {
    title: "Kisan Setu",
    subtitle: "AI Soil Test Analyst",
    loginBtn: "Login",
    signUpBtn: "Sign Up",
    phonePlaceholder: "Mobile Number",
    emailPlaceholder: "Email Address",
    passwordPlaceholder: "Password",
    usernamePlaceholder: "Username",
    emailOrUsernamePlaceholder: "Email or Username",
    noAccount: "Don't have an account?",
    haveAccount: "Already have an account?",
    next: "Next",
    back: "Back",
    submit: "Submit",
    uploadReport: "Upload Soil Test Report",
    dragDrop: "Ready to check your soil health? Click or drag your report image here to get an instant AI-generated analysis.",
    analyzing: "Analyzing report with AI...",
    village: "Village",
    taluka: "Taluka",
    district: "District",
    state: "State",
    crop: "Crop Grown/Proposed",
    soilType: "Soil Type",
    soilTexture: "Soil Texture",
    soilColor: "Soil Color",
    resultsTitle: "Analysis Report",
    retry: "Analyze Another",
    downloadReport: "Download Report",
    enterLocation: "Enter Location (Village/District)",
    directChatBtn: "Chat with Agri-Expert",
    chatTitle: "Agri-Assistant",
    chatSubtitle: "Ask about crops, schemes, ministries, or soil",
    chatPlaceholder: "Type your question here...",
    diseaseRisksTitle: "Potential Disease Risks",
    dashboardHome: "Home",
    dashboardNews: "Latest News",
    dashboardSchemes: "Govt Schemes",
    dashboardAnalysis: "Soil Test Analysis",
    menu: "Menu",
    welcomeMessage: "Welcome to Kisan Setu",
    appDescription: "Your intelligent companion for smarter farming. We analyze soil health and provide expert agricultural advice.",
    features: "Key Features",
    feature1: "Instant Soil Analysis",
    feature1Desc: "Simply upload a photo or PDF of your soil test report. Our advanced AI instantly reads and analyzes critical parameters like pH, Nitrogen, Phosphorus, and Potassium levels to give you a clear, easy-to-understand health card for your farm.",
    feature2: "Smart Fertilizer Plans",
    feature2Desc: "Receive personalized fertilizer recommendations that balance both chemical and organic options. We help you save costs on unnecessary inputs while maximizing your crop yields through scientifically backed nutrient management strategies.",
    feature3: "24/7 Agri-Expert Chat",
    feature3Desc: "Have questions about pests, weather, or government schemes? Chat with our intelligent Agri-Assistant in your local language 24/7. It provides instant, accurate answers and can even guide you through complex application processes.",
    logout: "Logout",
    newsTitle: "Agri-News & Updates",
    newsSubtitle: "Stay updated with real-time weather forecasts, market advisories, and the latest agricultural trends from trusted sources like IMD and eNAM.",
    fetchNews: "Get Latest Updates",
    locationPlaceholder: "Enter District (e.g., Pune, Nashik)",
    sources: "Sources",
    schemesTitle: "Government Schemes",
    schemesSubtitle: "Explore a comprehensive database of central and state government schemes. Find out about subsidies, eligibility criteria, and step-by-step application guidance.",
    fetchSchemes: "Find Schemes",
    benefitsLabel: "Benefits",
    stepsLabel: "How to Apply",
    applyLinkBtn: "Visit Official Portal",
    noReportBtn: "Don't have a report?",
    guideTitle: "Soil Testing Guide",
    guideSubtitle: "New to soil testing? Learn the correct method to take a soil sample, why it is crucial for your harvest, and how to interpret the results.",
    whyTestTitle: "Why Test Soil?",
    whyTestDesc: "Soil testing helps you save money on fertilizers, improve crop yield, and maintain soil health for future generations.",
    howToSampleTitle: "How to Take a Sample",
    step1Title: "Dig V-Shape",
    step1Desc: "Dig a V-shaped pit (6-8 inches deep) at 8-10 random spots in your field.",
    step2Title: "Collect Slice",
    step2Desc: "Take a 1-inch thick slice of soil from top to bottom of the pit.",
    step3Title: "Mix Well",
    step3Desc: "Mix all samples in a clean bucket. Remove stones and roots.",
    step4Title: "Pack & Label",
    step4Desc: "Take 500g of the mix, pack in a clean bag, and label with your details.",
    findLabBtn: "Find Nearby Labs",
    nearbyLabsTitle: "Nearby Labs & Centers",
    nearbyLabsSubtitle: "Find authorized Soil Testing Laboratories and Krushi Seva Kendras closest to your village. Get directions and contact details instantly.",
    locating: "Acquiring your location...",
    allowLocation: "Please allow location access to find nearby labs.",
    labsSection: "Soil Testing Labs",
    kendrasSection: "Krushi Seva Kendras",
    getDirections: "View on Map",
  },
  hi: {
    title: "किसान सेतु",
    subtitle: "AI मृदा परीक्षण विश्लेषक",
    loginBtn: "लॉग इन",
    signUpBtn: "साइन अप",
    phonePlaceholder: "मोबाइल नंबर",
    emailPlaceholder: "ईमेल पता",
    passwordPlaceholder: "पासवर्ड",
    usernamePlaceholder: "उपयोगकर्ता नाम",
    emailOrUsernamePlaceholder: "ईमेल या उपयोगकर्ता नाम",
    noAccount: "खाता नहीं है?",
    haveAccount: "पहले से खाता है?",
    next: "अगला",
    back: "वापस",
    submit: "जमा करें",
    uploadReport: "मृदा परीक्षण रिपोर्ट अपलोड करें",
    dragDrop: "यहाँ क्लिक करें या इमेज खींचें",
    analyzing: "AI रिपोर्ट का विश्लेषण कर रहा है...",
    village: "गाँव",
    taluka: "तालुका",
    district: "ज़िला",
    state: "राज्य",
    crop: "फसल (वर्तमान/प्रस्तावित)",
    soilType: "मिट्टी का प्रकार",
    soilTexture: "मिट्टी की बनावट",
    soilColor: "मिट्टी का रंग",
    resultsTitle: "विश्लेषण रिपोर्ट",
    retry: "दूसरा विश्लेषण करें",
    downloadReport: "रिपोर्ट डाउनलोड करें",
    enterLocation: "स्थान दर्ज करें (गाँव/ज़िला)",
    directChatBtn: "कृषि विशेषज्ञ से चैट करें",
    chatTitle: "कृषि सहायक",
    chatSubtitle: "फसल, योजनाएं, मंत्रालय या मिट्टी के बारे में पूछें",
    chatPlaceholder: "अपना सवाल यहाँ लिखें...",
    diseaseRisksTitle: "संभावित फसल रोग",
    dashboardHome: "होम",
    dashboardNews: "ताज़ा ख़बरें",
    dashboardSchemes: "सरकारी योजनाएं",
    dashboardAnalysis: "मृदा परीक्षण विश्लेषण",
    menu: "मेन्यू",
    welcomeMessage: "किसान सेतु में आपका स्वागत है",
    appDescription: "स्मार्ट खेती के लिए आपका बुद्धिमान साथी। हम मिट्टी के स्वास्थ्य का विश्लेषण करते हैं और विशेषज्ञ कृषि सलाह प्रदान करते हैं।",
    features: "मुख्य विशेषताएं",
    feature1: "त्वरित मिट्टी विश्लेषण",
    feature1Desc: "पोषक तत्वों और पीएच स्तरों के त्वरित, सटीक AI-संचालित विश्लेषण के लिए अपनी मृदा परीक्षण रिपोर्ट अपलोड करें।",
    feature2: "खाद योजनाएं",
    feature2Desc: "मिट्टी के आंकड़ों के आधार पर अपनी विशिष्ट फसल की पैदावार बढ़ाने के लिए जैविक और रासायनिक खाद की योजना प्राप्त करें।",
    feature3: "24/7 कृषि चैट",
    feature3Desc: "24 घंटे खेती की सलाह और सहायता के लिए अपनी स्थानीय भाषा में हमारे उन्नत कृषि-बोट से चैट करें।",
    logout: "लॉग आउट",
    newsTitle: "कृषि समाचार और अपडेट",
    newsSubtitle: "IMD, eNAM और सरकारी स्रोतों से नवीनतम अपडेट",
    fetchNews: "अपडेट प्राप्त करें",
    locationPlaceholder: "ज़िला दर्ज करें (जैसे: पुणे, नासिक)",
    sources: "स्रोत",
    schemesTitle: "सरकारी योजनाएं",
    schemesSubtitle: "लाभकारी योजनाएं, सब्सिडी और आवेदन विवरण खोजें",
    fetchSchemes: "योजनाएं खोजें",
    benefitsLabel: "लाभ",
    stepsLabel: "आवेदन कैसे करें",
    applyLinkBtn: "आधिकारिक पोर्टल पर जाएं",
    noReportBtn: "रिपोर्ट नहीं है?",
    guideTitle: "मृदा परीक्षण गाइड",
    guideSubtitle: "परीक्षण क्यों महत्वपूर्ण है और कैसे करें",
    whyTestTitle: "मिट्टी की जाँच क्यों?",
    whyTestDesc: "मिट्टी की जाँच खाद पर पैसा बचाने, फसल की पैदावार बढ़ाने और मिट्टी के स्वास्थ्य को बनाए रखने में मदद करती है।",
    howToSampleTitle: "नमूना कैसे लें",
    step1Title: "V-आकार का गड्ढा",
    step1Desc: "अपने खेत में 8-10 यादृच्छिक स्थानों पर एक V-आकार का गड्ढा (6-8 इंच गहरा) खोदें।",
    step2Title: "मिट्टी निकालें",
    step2Desc: "गड्ढे के ऊपर से नीचे तक मिट्टी की 1 इंच मोटी परत निकालें।",
    step3Title: "अच्छी तरह मिलाएं",
    step3Desc: "सभी नमूनों को एक साफ बाल्टी में मिलाएं। पत्थर और जड़ें हटा दें।",
    step4Title: "पैक करें और लेबल लगाएं",
    step4Desc: "मिश्रण में से 500 ग्राम लें, एक साफ थैली में पैक करें और अपना विवरण लिखें।",
    findLabBtn: "नज़दीकी लैब खोजें",
    nearbyLabsTitle: "नज़दीकी लैब और केंद्र",
    nearbyLabsSubtitle: "आपके पास की सुविधाएं खोजी जा रही हैं...",
    locating: "आपका स्थान प्राप्त किया जा रहा है...",
    allowLocation: "कृपया नज़दीकी लैब खोजने के लिए स्थान की अनुमति दें।",
    labsSection: "मृदा परीक्षण लैब",
    kendrasSection: "कृषि सेवा केंद्र",
    getDirections: "मैप पर देखें",
  },
  mr: {
    title: "किसान सेतु",
    subtitle: "AI मृदा चाचणी विश्लेषक",
    loginBtn: "लॉग इन",
    signUpBtn: "साइन अप",
    phonePlaceholder: "मोबाईल नंबर",
    emailPlaceholder: "ईमेल",
    passwordPlaceholder: "पासवर्ड",
    usernamePlaceholder: "वापरकर्तानाव",
    emailOrUsernamePlaceholder: "ईमेल किंवा वापरकर्तानाव",
    noAccount: "खाते नाही?",
    haveAccount: "आधीच खाते आहे?",
    next: "पुढील",
    back: "मागे",
    submit: "सादर करा",
    uploadReport: "माती परीक्षण अहवाल अपलोड करें",
    dragDrop: "येथे क्लिक करा किंवा इमेज ओढा",
    analyzing: "AI अहवालाचे विश्लेषण करत आहे...",
    village: "गाव",
    taluka: "तालुका",
    district: "जिल्हा",
    state: "राज्य",
    crop: "पीक (सध्याचे/प्रस्तावित)",
    soilType: "मातीचा प्रकार",
    soilTexture: "मातीचा पोत",
    soilColor: "मातीचा रंग",
    resultsTitle: "विश्लेषण अहवाल",
    retry: "दुसरे विश्लेषण करा",
    downloadReport: "अहवाल डाउनलोड करा",
    enterLocation: "स्थान प्रविष्ट करा (गाव/जिल्हा)",
    directChatBtn: "कृषी तज्ञांशी गप्पा मारा",
    chatTitle: "कृषी सहाय्यक",
    chatSubtitle: "पीक, योजना, मंत्रालय किंवा मातीबद्दल विचारा",
    chatPlaceholder: "तुमचा प्रश्न येथे टाईप करा...",
    diseaseRisksTitle: "संभावित पीक रोग",
    dashboardHome: "होम",
    dashboardNews: "ताज्या बातम्या",
    dashboardSchemes: "सरकारी योजना",
    dashboardAnalysis: "मृदा चाचणी विश्लेषण",
    menu: "मेनू",
    welcomeMessage: "किसान सेतु मध्ये आपले स्वागत आहे",
    appDescription: "स्मार्ट शेतीसाठी तुमचा हुशार साथीदार. आम्ही मातीचे आरोग्य तपासतो आणि तज्ञ कृषी सल्ला देतो.",
    features: "मुख्य वैशिष्ट्ये",
    feature1: "त्वरित माती विश्लेषण",
    feature1Desc: "पोषक तत्वे आणि पीएच पातळीच्या त्वरित आणि अचूक AI विश्लेषणासाठी आपल्या माती परीक्षण अहवालाचा फोटो अपलोड करा.",
    feature2: "खत नियोजन",
    feature2Desc: "मातीचा अहवाल पाहून आपल्या पिकाचे उत्पन्न वाढवण्यासाठी सेंद्रीय आणि रासायनिक खतांचे नियोजन मिळवा.",
    feature3: "24/7 कृषी-चॅट",
    feature3Desc: "चोवीस तास शेतीविषयक सल्ल्यासाठी आपल्या स्थानिक भाषेत आमच्या प्रगत ॲग्री-बोटशी गप्पा मारा.",
    logout: "लॉग आउट",
    newsTitle: "कृषि बातम्या आणि अपडेट्स",
    newsSubtitle: "IMD, eNAM आणि सरकारी स्रोतांकडून नवीनतम अपडेट्स",
    fetchNews: "अपडेट्स मिळवा",
    locationPlaceholder: "जिल्हा प्रविष्ट करा (उदा. पुणे, नासिक)",
    sources: "स्रोत",
    schemesTitle: "सरकारी योजना",
    schemesSubtitle: "फायदेशीर योजना, सबसिडी आणि अर्जाचा तपशील शोधा",
    fetchSchemes: "योजना शोधा",
    benefitsLabel: "फायदे",
    stepsLabel: "अर्ज कसा करावा",
    applyLinkBtn: "अधिकृत पोर्टलला भेट द्या",
    noReportBtn: "अहवाल नाही?",
    guideTitle: "माती परीक्षण मार्गदर्शक",
    guideSubtitle: "चाचणी का महत्त्वाची आहे आणि ती कशी करावी",
    whyTestTitle: "माती परीक्षण का?",
    whyTestDesc: "माती परीक्षण खतांवर पैसे वाचविण्यास, पिकाचे उत्पन्न वाढविण्यास आणि मातीचे आरोग्य राखण्यास मदत करते.",
    howToSampleTitle: "नमुना कसा घ्यावा",
    step1Title: "V-आकाराचा खड्डा",
    step1Desc: "शेतात ८-१० ठिकाणी V-आकाराचा खड्डा (६-८ इंच खोल) खणा.",
    step2Title: "माती काढा",
    step2Desc: "खड्ड्याच्या वरपासून तळापर्यंत १ इंच जाडीचा मातीचा थर काढा.",
    step3Title: "चांगले मिसळा",
    step3Desc: "सर्व नमुने एका स्वच्छ बादलीत मिसळा. दगड आणि मुळे काढून टाका.",
    step4Title: "पॅक करा आणि लेबल लावा",
    step4Desc: "मिश्रणातून ५०० ग्रॅम घ्या, स्वच्छ पिशवीत भरा आणि त्यावर तुमचे नाव लिहा.",
    findLabBtn: "जवळची लॅब शोधा",
    nearbyLabsTitle: "जवळच्या लॅब आणि केंद्रे",
    nearbyLabsSubtitle: "तुमच्या जवळच्या सुविधा शोधत आहे...",
    locating: "तुमचे स्थान मिळवत आहे...",
    allowLocation: "कृपया जवळच्या लॅब शोधण्यासाठी लोकेशनची परवानगी द्या.",
    labsSection: "माती परीक्षण लॅब",
    kendrasSection: "कृषी सेवा केंद्र",
    getDirections: "मॅपवर पहा",
  },
  ur: {
    title: "کسان سیتو",
    subtitle: "AI مٹی ٹیسٹ تجزیہ کار",
    loginBtn: "لاگ ان",
    signUpBtn: "سائن اپ",
    phonePlaceholder: "موبائل نمبر",
    emailPlaceholder: "ای میل",
    passwordPlaceholder: "پاس ورڈ",
    usernamePlaceholder: "صارف کا نام",
    emailOrUsernamePlaceholder: "ای میل یا صارف کا نام",
    noAccount: "اکاؤنٹ نہیں ہے؟",
    haveAccount: "پہلے سے اکاؤنٹ ہے؟",
    next: "اگلا",
    back: "پیچھے",
    submit: "جمع کرائیں",
    uploadReport: "مٹی ٹیسٹ رپورٹ اپ لوڈ کریں",
    dragDrop: "یہاں کلک کریں یا تصویر ڈریگ کریں",
    analyzing: "AI رپورٹ کا تجزیہ کر رہا ہے...",
    village: "گاؤں",
    taluka: "تعلقہ",
    district: "ضلع",
    state: "ریاست",
    crop: "فصل (موجودہ/تجویز کردہ)",
    soilType: "مٹی کی قسم",
    soilTexture: "مٹی کی ساخت",
    soilColor: "مٹی کا رنگ",
    resultsTitle: "تجزیاتی رپورٹ",
    retry: "دوسرا تجزیہ کریں",
    downloadReport: "رپورٹ ڈاؤن لوڈ کریں",
    enterLocation: "مقام درج کریں (گاؤں/ضلع)",
    directChatBtn: "زرعی ماہر سے بات کریں",
    chatTitle: "زرعی معاون",
    chatSubtitle: "فصل، اسکیموں، وزارت یا مٹی کے بارے میں پوچھیں",
    chatPlaceholder: "اپنا سوال یہاں لکھیں...",
    diseaseRisksTitle: "ممکنہ فصل کی بیماریاں",
    dashboardHome: "ہوم",
    dashboardNews: "تازہ ترین خبریں",
    dashboardSchemes: "سرکاری اسکیمیں",
    dashboardAnalysis: "مٹی ٹیسٹ تجزیہ",
    menu: "مینو",
    welcomeMessage: "کسان سیتو میں خوش آمدید",
    appDescription: "اسمارٹ فارمنگ کے لیے آپ کا ذہین ساتھی۔ ہم مٹی کی صحت کا تجزیہ کرتے ہیں اور ماہرانہ زرعی مشورے فراہم کرتے ہیں.",
    features: "اہم خصوصیات",
    feature1: "فوری مٹی کا تجزیہ",
    feature1Desc: "فوری اور درست AI تجزیہ کے لیے اپنی مٹی کے ٹیسٹ کی رپورٹ کی تصویر اپ لوڈ کریں۔",
    feature2: "کھاد کے منصوبے",
    feature2Desc: "اپنی مخصوص فصل کی پیداوار بڑھانے کے لیے نامیاتی اور کیمیائی کھاد کے منصوبے حاصل کریں۔",
    feature3: "24/7 زرعی چیٹ",
    feature3Desc: "24/7 کاشتکاری کے مشورے کے لیے اپنی مقامی زبان میں ہمارے زرعی بوٹ سے بات کریں۔",
    logout: "لاگ آؤٹ",
    newsTitle: "زرعی خبریں اور اپ ڈیٹس",
    newsSubtitle: "IMD، eNAM اور سرکاری ذرائع سے تازہ ترین اپ ڈیٹس",
    fetchNews: "اپ ڈیٹس حاصل کریں",
    locationPlaceholder: "ضلع درج کریں (جیسے پونے، ناسک)",
    sources: "ذرائع",
    schemesTitle: "سرکاری اسکیمیں",
    schemesSubtitle: "فائدہ مند اسکیمیں، سبسڈیز اور درخواست کی تفصیلات تلاش کریں",
    fetchSchemes: "اسکیمیں تلاش کریں",
    benefitsLabel: "فوائد",
    stepsLabel: "درخواست دینے کا طریقہ",
    applyLinkBtn: "سرکاری پورٹل پر جائیں",
    noReportBtn: "رپورٹ نہیں ہے؟",
    guideTitle: "مٹی ٹیسٹ گائیڈ",
    guideSubtitle: "جانچ کیوں اہم ہے اور کیسے کریں",
    whyTestTitle: "مٹی کا ٹیسٹ کیوں؟",
    whyTestDesc: "مٹی کا ٹیسٹ کھاد پر پیسے بچانے، فصل کی پیداوار بڑھانے اور مٹی کی صحت برقرار رکھنے میں مدد کرتا ہے۔",
    howToSampleTitle: "نمونہ کیسے لیں",
    step1Title: "V-شکل کا گڑھا",
    step1Desc: "کھیت میں 8-10 جگہوں پر V-شکل کا گڑھا (6-8 انچ گہرا) کھودیں۔",
    step2Title: "مٹی نکالیں",
    step2Desc: "گڑھے کے اوپر سے نیچے تک 1 انچ موٹی مٹی کی تہہ نکالیں۔",
    step3Title: "اچھی طرح مکس کریں",
    step3Desc: "تمام نمونوں کو صاف بالٹی میں ملائیں۔ پتھر اور جڑیں نکال دیں۔",
    step4Title: "پیک اور لیبل",
    step4Desc: "مکس میں سے 500 گرام لیں، صاف تھیلی میں پیک کریں اور اپنی تفصیلات لکھیں۔",
    findLabBtn: "قریبی لیب تلاش کریں",
    nearbyLabsTitle: "قریبی لیبز اور مراکز",
    nearbyLabsSubtitle: "آپ کے قریب سہولیات تلاش کی جا رہی ہیں...",
    locating: "آپ کا مقام حاصل کیا جا رہا ہے...",
    allowLocation: "براہ کرم قریبی لیب تلاش کرنے کے لیے مقام کی اجازت دیں۔",
    labsSection: "مٹی ٹیسٹ لیب",
    kendrasSection: "کرشی سیوا کیندر",
    getDirections: "نقشے پر دیکھیں",
  },
  kn: {
    title: "ಕಿಸಾನ್ ಸೇತು",
    subtitle: "AI ಮಣ್ಣು ಪರೀಕ್ಷೆ ವಿಶ್ಲೇಷಕ",
    loginBtn: "ಲಾಗಿನ್",
    signUpBtn: "ಸೈನ್ ಅಪ್",
    phonePlaceholder: "ಮೊಬೈಲ್ ಸಂಖ್ಯೆ",
    emailPlaceholder: "ಇಮೇಲ್",
    passwordPlaceholder: "ಪಾಸ್ವರ್ಡ್",
    usernamePlaceholder: "ಬಳಕೆದಾರ ಹೆಸರು",
    emailOrUsernamePlaceholder: "ಇಮೇಲ್ ಅಥವಾ ಬಳಕೆದಾರ ಹೆಸರು",
    noAccount: "ಖಾತೆ ಇಲ್ಲವೇ?",
    haveAccount: "ಈಗಾಗಲೇ ಖಾತೆ ಇದೆಯೇ?",
    next: "ಮುಂದೆ",
    back: "ಹಿಂದೆ",
    submit: "ಸಲ್ಲಿಸಿ",
    uploadReport: "ಮಣ್ಣು ಪರೀಕ್ಷೆ ವರದಿ ಅಪ್‌ಲೋಡ್ ಮಾಡಿ",
    dragDrop: "ಇಲ್ಲಿ ಕ್ಲಿಕ್ ಮಾಡಿ ಅಥವಾ ಚಿತ್ರವನ್ನು ಎಳೆಯಿರಿ",
    analyzing: "AI ವರದಿಯನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತಿದೆ...",
    village: "ಗ್ರಾಮ",
    taluka: "ತಾಲ್ಲೂಕು",
    district: "ಜಿಲ್ಲೆ",
    state: "ರಾಜ್ಯ",
    crop: "ಬೆಳೆ (ಪ್ರಸ್ತುತ/ಪ್ರಸ್ತಾವಿತ)",
    soilType: "ಮಣ್ಣಿನ ವಿಧ",
    soilTexture: "ಮಣ್ಣಿನ ರಚನೆ",
    soilColor: "ಮಣ್ಣಿನ ಬಣ್ಣ",
    resultsTitle: "ವಿಶ್ಲೇಷಣೆ ವರದಿ",
    retry: "ಮತ್ತೊಂದು ವಿಶ್ಲೇಷಿಸಿ",
    downloadReport: "ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    enterLocation: "ಸ್ಥಳವನ್ನು ನಮೂದಿಸಿ (ಗ್ರಾಮ/ಜಿಲ್ಲೆ)",
    directChatBtn: "ಕೃಷಿ ತಜ್ಞರೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ",
    chatTitle: "ಕೃಷಿ ಸಹಾಯಕ",
    chatSubtitle: "ಬೆಳೆಗಳು, ಯೋಜನೆಗಳು, ಸಚಿವಾಲಯ ಅಥವಾ ಮಣ್ಣಿನ ಬಗ್ಗೆ ಕೇಳಿ",
    chatPlaceholder: "ನಿಮ್ಮ ಪ್ರಶ್ನೆಯನ್ನು ಇಲ್ಲಿ ಟೈಪ್ ಮಾಡಿ...",
    diseaseRisksTitle: "ಸಂಭವನೀಯ ಬೆಳೆ ರೋಗಗಳು",
    dashboardHome: "ಹೋಮ್",
    dashboardNews: "ತಾಜಾ ಸುದ್ದಿ",
    dashboardSchemes: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    dashboardAnalysis: "ಮಣ್ಣು ಪರೀಕ್ಷೆ ವಿಶ್ಲೇಷಣೆ",
    menu: "ಮೆನು",
    welcomeMessage: "ಕಿಸಾನ್ ಸೇತುಗೆ ಸುಸ್ವಾಗತ",
    appDescription: "ಸ್ಮಾರ್ಟ್ ಕೃಷಿಗಾಗಿ ನಿಮ್ಮ ಬುದ್ಧಿವಂತ ಸಂಗಾತಿ. ನಾವು ಮಣ್ಣಿನ ಆರೋಗ್ಯವನ್ನು ವಿಶ್ಲೇಷಿಸುತ್ತೇವೆ ಮತ್ತು ತಜ್ಞ ಕೃಷಿ ಸಲಹೆಯನ್ನು ನೀಡುತ್ತೇವೆ.",
    features: "ಪ್ರಮುಖ ಲಕ್ಷಣಗಳು",
    feature1: "ತ್ವರಿತ ಮಣ್ಣಿನ ವಿಶ್ಲೇಷಣೆ",
    feature1Desc: "ತ್ವರಿತ ಮತ್ತು ನಿಖರವಾದ AI ವಿಶ್ಲೇಷಣೆಗಾಗಿ ನಿಮ್ಮ ಮಣ್ಣು ಪರೀಕ್ಷಾ ವರದಿಯ ಫೋಟೋವನ್ನು ಅಪ್‌ಲೋಡ್ ಮಾಡಿ.",
    feature2: "ರಸಗೊಬ್ಬರ ಯೋಜನೆಗಳು",
    feature2Desc: "ನಿಮ್ಮ ನಿರ್ದಿಷ್ಟ ಬೆಳೆ ಇಳುವರಿಯನ್ನು ಹೆಚ್ಚಿಸಲು ಸಾವಯವ ಮತ್ತು ರಾಸಾಯನಿಕ ಗೊಬ್ಬರ ಯೋಜನೆಗಳನ್ನು ಪಡೆಯಿರಿ.",
    feature3: "24/7 ಕೃಷಿ-ಚಾಟ್",
    feature3Desc: "24/7 ಕೃಷಿ ಸಲಹೆಗಾಗಿ ನಿಮ್ಮ ಸ್ಥಳೀಯ ಭಾಷೆಯಲ್ಲಿ ನಮ್ಮ ಕೃಷಿ-ಬಾಟ್‌ನೊಂದಿಗೆ ಚಾಟ್ ಮಾಡಿ.",
    logout: "ಲಾಗ್ ಔಟ್",
    newsTitle: "ಕೃಷಿ ಸುದ್ದಿ ಮತ್ತು ನವೀಕರಣಗಳು",
    newsSubtitle: "IMD, eNAM ಮತ್ತು ಸರ್ಕಾರಿ ಮೂಲಗಳಿಂದ ಇತ್ತೀಚಿನ ನವೀಕರಣಗಳು",
    fetchNews: "ನವೀಕರಣಗಳನ್ನು ಪಡೆಯಿರಿ",
    locationPlaceholder: "ಜಿಲ್ಲೆಯನ್ನು ನಮೂದಿಸಿ (ಉದಾ. ಪುಣೆ, ನಾಸಿಕ್)",
    sources: "ಮೂಲಗಳು",
    schemesTitle: "ಸರ್ಕಾರಿ ಯೋಜನೆಗಳು",
    schemesSubtitle: "ಲಾಭದಾಯಕ ಯೋಜನೆಗಳು, ಸಬ್ಸಿಡಿಗಳು ಮತ್ತು ಅರ್ಜಿಯ ವಿವರಗಳನ್ನು ಹುಡುಕಿ",
    fetchSchemes: "ಯೋಜನೆಗಳನ್ನು ಹುಡುಕಿ",
    benefitsLabel: "ಪ್ರಯೋಜನಗಳು",
    stepsLabel: "ಅರ್ಜಿ ಸಲ್ಲಿಸುವುದು ಹೇಗೆ",
    applyLinkBtn: "ಅಧಿಕೃತ ಪೋರ್ಟಲ್‌ಗೆ ಭೇಟಿ ನೀಡಿ",
    noReportBtn: "ವರದಿ ಇಲ್ಲವೇ?",
    guideTitle: "ಮಣ್ಣು ಪರೀಕ್ಷೆ ಮಾರ್ಗದರ್ಶಿ",
    guideSubtitle: "ಪರೀಕ್ಷೆ ಏಕೆ ಮುಖ್ಯ ಮತ್ತು ಹೇಗೆ ಮಾಡುವುದು",
    whyTestTitle: "ಮಣ್ಣು ಪರೀಕ್ಷೆ ಏಕೆ?",
    whyTestDesc: "ಮಣ್ಣು ಪರೀಕ್ಷೆಯು ಗೊಬ್ಬರದ ಮೇಲೆ ಹಣ ಉಳಿಸಲು, ಬೆಳೆ ಇಳುವರಿ ಹೆಚ್ಚಿಸಲು ಮತ್ತು ಮಣ್ಣಿನ ಆರೋಗ್ಯ ಕಾಪಾಡಲು ಸಹಾಯ ಮಾಡುತ್ತದೆ.",
    howToSampleTitle: "ಮಾದರಿ ತೆಗೆಯುವುದು ಹೇಗೆ",
    step1Title: "V-ಆಕಾರದ ಗುಂಡಿ",
    step1Desc: "ಹೊಲದಲ್ಲಿ 8-10 ಕಡೆ V-ಆಕಾರದ ಗುಂಡಿ (6-8 ಇಂಚು ಆಳ) ಅಗೆಯಿರಿ.",
    step2Title: "ಮಣ್ಣು ಸಂಗ್ರಹಿಸಿ",
    step2Desc: "ಗುಂಡಿಯ ಮೇಲಿಂದ ಕೆಳಗಿನವರೆಗೆ 1 ಇಂಚು ದಪ್ಪದ ಮಣ್ಣಿನ ಪದರವನ್ನು ತೆಗೆಯಿರಿ.",
    step3Title: "ಚನ್ನಾಗಿ ಮಿಶ್ರಣ ಮಾಡಿ",
    step3Desc: "ಎಲ್ಲಾ ಮಾದರಿಗಳನ್ನು ಸ್ವಚ್ಛ ಬಕೆಟ್‌ನಲ್ಲಿ ಮಿಶ್ರಣ ಮಾಡಿ. ಕಲ್ಲು ಮತ್ತು ಬೇರುಗಳನ್ನು ತೆಗೆಯಿರಿ.",
    step4Title: "ಪ್ಯಾಕ್ ಮಾಡಿ ಮತ್ತು ಲೇಬಲ್ ಮಾಡಿ",
    step4Desc: "ಮಿಶ್ರಣದಿಂದ 500 ಗ್ರಾಂ ತೆಗೆದುಕೊಂಡು, ಸ್ವಚ್ಛ ಚೀಲದಲ್ಲಿ ಹಾಕಿ ಮತ್ತು ನಿಮ್ಮ ವಿವರಗಳನ್ನು ಬರೆಯಿರಿ.",
    findLabBtn: "ಹತ್ತಿರದ ಲ್ಯಾಬ್‌ಗಳನ್ನು ಹುಡುಕಿ",
    nearbyLabsTitle: "ಹತ್ತಿರದ ಲ್ಯಾಬ್‌ಗಳು ಮತ್ತು ಕೇಂದ್ರಗಳು",
    nearbyLabsSubtitle: "ನಿಮ್ಮ ಹತ್ತಿರದ ಸೌಲಭ್ಯಗಳನ್ನು ಹುಡುಕಲಾಗುತ್ತಿದೆ...",
    locating: "ನಿಮ್ಮ ಸ್ಥಳವನ್ನು ಪಡೆಯಲಾಗುತ್ತಿದೆ...",
    allowLocation: "ಹತ್ತಿರದ ಲ್ಯಾಬ್‌ಗಳನ್ನು ಹುಡುಕಲು ದಯವಿಟ್ಟು ಸ್ಥಳ ಪ್ರವೇಶವನ್ನು ಅನುಮತಿಸಿ.",
    labsSection: "ಮಣ್ಣು ಪರೀಕ್ಷೆ ಲ್ಯಾಬ್",
    kendrasSection: "ಕೃಷಿ ಸೇವಾ ಕೇಂದ್ರಗಳು",
    getDirections: "ಮ್ಯಾಪ್‌ನಲ್ಲಿ ನೋಡಿ",
  },
  te: {
    title: "కిసాన్ సేతు",
    subtitle: "AI మట్టి పరీక్ష విశ్లేషకుడు",
    loginBtn: "లాగిన్",
    signUpBtn: "సైన్ అప్",
    phonePlaceholder: "మొబైల్ నంబర్",
    emailPlaceholder: "ఇమెయిల్",
    passwordPlaceholder: "పాస్‌వర్డ్",
    usernamePlaceholder: "వినియోగదారు పేరు",
    emailOrUsernamePlaceholder: "ఇమెయిల్ లేదా వినియోగదారు పేరు",
    noAccount: "ఖాతా లేదా?",
    haveAccount: "అప్పటికే ఖాతా ఉందా?",
    next: "తరువాత",
    back: "వెనుకకు",
    submit: "సమర్పించండి",
    uploadReport: "మట్టి పరీక్ష నివేదికను అప్‌లోడ్ చేయండి",
    dragDrop: "ఇక్కడ క్లిక్ చేయండి లేదా చిత్రాన్ని లాగండి",
    analyzing: "AI నివేదికను విశ్లేషిస్తోంది...",
    village: "గ్రామం",
    taluka: "తాలూకా",
    district: "జిల్లా",
    state: "రాష్ట్రం",
    crop: "పంట (ప్రస్తుత/ప్రతిపాదిత)",
    soilType: "మట్టి రకం",
    soilTexture: "మట్టి ఆకృతి",
    soilColor: "మట్టి రంగు",
    resultsTitle: "విశ్లేషణ నివేదిక",
    retry: "మరొకటి విశ్లేషించండి",
    downloadReport: "నివేదిక డౌన్‌లోడ్ చేయండి",
    enterLocation: "స్థానాన్ని నమోదు చేయండి (గ్రామం/జిల్లా)",
    directChatBtn: "వ్యవసాయ నిపుణుడితో చాట్ చేయండి",
    chatTitle: "వ్యవసాయ సహాయకుడు",
    chatSubtitle: "పంటలు, పథకాలు, మంత్రిత్వ శాఖ లేదా మట్టి గురించి అడగండి",
    chatPlaceholder: "మీ ప్రశ్నను ఇక్కడ టైప్ చేయండి...",
    diseaseRisksTitle: "సంభావ్య పంట వ్యాధులు",
    dashboardHome: "హోమ్",
    dashboardNews: "తాజా వార్తలు",
    dashboardSchemes: "ప్రభుత్వ పథకాలు",
    dashboardAnalysis: "మట్టి పరీక్ష విశ్లేషణ",
    menu: "మెనూ",
    welcomeMessage: "కిసాన్ సేతుకు స్వాగతం",
    appDescription: "స్మార్ట్ వ్యవసాయానికి మీ తెలివైన సహచరుడు. మేము మట్టి ఆరోగ్యాన్ని విశ్లేషిస్తాము మరియు నిపుణుల వ్యవసాయ సలహాలను అందిస్తాము.",
    features: "ముఖ్య లక్షణాలు",
    feature1: "తక్షణ మట్టి విశ్లేషణ",
    feature1Desc: "తక్షణ మరియు ఖచ్చితమైన AI విశ్లేషణ కోసం మీ మట్టి పరీక్ష నివేదిక ఫోటోను అప్‌లోడ్ చేయండి.",
    feature2: "ఎరువుల ప్రణాళికలు",
    feature2Desc: "మీ నిర్దిష్ట పంట దిగుబడిని పెంచడానికి సేంద్రీయ మరియు రసాయన ఎరువుల ప్రణాళికలను పొందండి.",
    feature3: "24/7 అగ్రి-చాట్",
    feature3Desc: "24/7 వ్యవసాయ సలహా కోసం మీ స్థానిక భాషలో మా అగ్రి-బాట్‌తో చాట్ చేయండి.",
    logout: "లాగ్ అవుట్",
    newsTitle: "వ్యవసాయ వార్తలు & నవీకరణలు",
    newsSubtitle: "IMD, eNAM & ప్రభుత్వ మూలాల నుండి తాజా నవీకరణలు",
    fetchNews: "తాజా నవీకరణలను పొందండి",
    locationPlaceholder: "జిల్లాను నమోదు చేయండి (ఉదా. పూణే, నాసిక్)",
    sources: "మూలాలు",
    schemesTitle: "ప్రభుత్వ పథకాలు",
    schemesSubtitle: "ప్రయోజనకరమైన పథకాలు, సబ్సిడీలు & దరఖాస్తు వివరాలను కనుగొనండి",
    fetchSchemes: "పథకాలను కనుగొనండి",
    benefitsLabel: "ప్రయోజనాలు",
    stepsLabel: "దరఖాస్తు విధానం",
    applyLinkBtn: "అధికారిక పోర్టల్‌ను సందర్శించండి",
    noReportBtn: "నివేదిక లేదా?",
    guideTitle: "మట్టి పరీక్ష గైడ్",
    guideSubtitle: "పరీక్ష ఎందుకు ముఖ్యం & ఎలా చేయాలి",
    whyTestTitle: "మట్టిని ఎందుకు పరీక్షించాలి?",
    whyTestDesc: "మట్టి పరీక్ష ఎరువులపై డబ్బు ఆదా చేయడానికి, పంట దిగుబడిని పెంచడానికి మరియు మట్టి ఆరోగ్యాన్ని కాపాడటానికి సహాయపడుతుంది.",
    howToSampleTitle: "నమూనా ఎలా తీసుకోవాలి",
    step1Title: "V-ఆకారపు గుంత",
    step1Desc: "పొలంలో 8-10 చోట్ల V-ఆకారపు గుంత (6-8 అంగుళాల లోతు) తవ్వండి.",
    step2Title: "మట్టిని తీయండి",
    step2Desc: "గుంత పైనుండి కింద వరకు 1 అంగుళం మందం ఉన్న మట్టి పొరను తీయండి.",
    step3Title: "బాగా కలపండి",
    step3Desc: "అన్ని నమూనాలను శుభ్రమైన బకెట్‌లో కలపండి. రాళ్లు, వేర్లను తొలగించండి.",
    step4Title: "ప్యాక్ & లేబుల్",
    step4Desc: "మిశ్రమం నుండి 500 గ్రాములు తీసుకోండి, శుభ్రమైన సంచిలో ప్యాక్ చేసి మీ వివరాలు రాయండి.",
    findLabBtn: "సమీప ల్యాబ్‌లను కనుగొనండి",
    nearbyLabsTitle: "సమీప ల్యాబ్‌లు & కేంద్రాలు",
    nearbyLabsSubtitle: "మీ దగ్గర సౌకర్యాలను గుర్తిస్తోంది...",
    locating: "మీ స్థానాన్ని పొందుతోంది...",
    allowLocation: "దయచేసి సమీప ల్యాబ్‌లను కనుగొనడానికి స్థాన ప్రాప్యతను అనుమతించండి.",
    labsSection: "మట్టి పరీక్షా ల్యాబ్",
    kendrasSection: "కృషి సేవా కేంద్రాలు",
    getDirections: "మ్యాప్‌లో వీక్షించండి",
  }
};